"""Unsloth runtime integration."""

from __future__ import annotations

from .batching import _BatchPlan
from .checkpoint_io import (
    _checkpoint_target,
    _save_weights,
    _validate_checkpoint_manifest,
    load_state,
    load_state_with_optimizer,
    save_sampler_with_download_url,
    save_state,
    save_weights_for_sampler,
)
from .core import UnslothEngine
from .generation import (
    _apply_top_k_top_p,
    _completion_logprobs_batch,
    _completion_logprobs_from_generate_scores,
    _encode_text,
    _ends_with_stop,
    _finish_reason,
    _generate,
    _generate_with_forward_loop,
    _generate_with_transformers_generate,
    _generated_logprobs,
    _next_sampled_token,
    _prompt_logprobs,
    _stop_token_ids,
    _token_logprobs,
    _trim_at_first_stop,
    _trim_stop_tokens,
    compute_logprobs,
    sample,
)
from .loading import (
    _best_attn_backend,
    _configure_unsloth_environment,
    _effective_attn_implementation,
    _effective_fast_inference,
    _effective_gpu_memory_utilization,
    _effective_vllm_standby,
    _flash_attention_2_available,
    _flash_attention_3_available,
    _gpu_compute_capability,
    _load_model,
    _model_device,
    _module_available,
    _padding_free_forced,
    _padding_free_requested,
    _requires_transformers_5_for_qwen3_5,
    _set_attention_implementation,
    _setup_distributed,
    _speed,
    _torch_dtype,
    _unwrap_model,
    _wrap_distributed_model,
    get_info,
    get_tokenizer,
    register_custom_loss,
)
from .losses_glue import (
    _batch_from_data,
    _cross_entropy_loss,
    _cross_entropy_loss_for_plan,
    _ensure_optimizer,
    _label_rows_from_data,
    _logit_position,
    _loss_fn_outputs,
    _loss_tensor_data,
    _loss_tokens,
    _model_forward,
    _policy_loss,
    _policy_loss_for_plan,
    _weighted_positions_to_keep,
    forward,
    forward_backward,
    forward_backward_custom,
    optim_step,
)

for _name, _fn in {
    "_setup_distributed": _setup_distributed,
    "_wrap_distributed_model": _wrap_distributed_model,
    "_unwrap_model": _unwrap_model,
    "_load_model": _load_model,
    "_speed": _speed,
    "_effective_fast_inference": _effective_fast_inference,
    "_effective_vllm_standby": _effective_vllm_standby,
    "_effective_gpu_memory_utilization": _effective_gpu_memory_utilization,
    "_effective_attn_implementation": _effective_attn_implementation,
    "_gpu_compute_capability": _gpu_compute_capability,
    "_best_attn_backend": _best_attn_backend,
    "_configure_unsloth_environment": _configure_unsloth_environment,
    "_padding_free_requested": _padding_free_requested,
    "_padding_free_forced": _padding_free_forced,
    "_set_attention_implementation": _set_attention_implementation,
    "get_tokenizer": get_tokenizer,
    "get_info": get_info,
    "register_custom_loss": register_custom_loss,
    "_ensure_optimizer": _ensure_optimizer,
    "_batch_from_data": _batch_from_data,
    "_loss_tensor_data": _loss_tensor_data,
    "_label_rows_from_data": _label_rows_from_data,
    "_loss_tokens": _loss_tokens,
    "_model_forward": _model_forward,
    "_weighted_positions_to_keep": _weighted_positions_to_keep,
    "_logit_position": _logit_position,
    "_cross_entropy_loss": _cross_entropy_loss,
    "_cross_entropy_loss_for_plan": _cross_entropy_loss_for_plan,
    "_policy_loss": _policy_loss,
    "_policy_loss_for_plan": _policy_loss_for_plan,
    "_loss_fn_outputs": _loss_fn_outputs,
    "forward": forward,
    "forward_backward": forward_backward,
    "forward_backward_custom": forward_backward_custom,
    "optim_step": optim_step,
    "_token_logprobs": _token_logprobs,
    "compute_logprobs": compute_logprobs,
    "sample": sample,
    "_generate": _generate,
    "_generate_with_transformers_generate": _generate_with_transformers_generate,
    "_completion_logprobs_from_generate_scores": _completion_logprobs_from_generate_scores,
    "_completion_logprobs_batch": _completion_logprobs_batch,
    "_generate_with_forward_loop": _generate_with_forward_loop,
    "_next_sampled_token": _next_sampled_token,
    "_apply_top_k_top_p": _apply_top_k_top_p,
    "_ends_with_stop": _ends_with_stop,
    "_encode_text": _encode_text,
    "_stop_token_ids": _stop_token_ids,
    "_trim_stop_tokens": _trim_stop_tokens,
    "_trim_at_first_stop": _trim_at_first_stop,
    "_finish_reason": _finish_reason,
    "_generated_logprobs": _generated_logprobs,
    "_prompt_logprobs": _prompt_logprobs,
    "_save_weights": _save_weights,
    "_checkpoint_target": _checkpoint_target,
    "save_state": save_state,
    "load_state": load_state,
    "load_state_with_optimizer": load_state_with_optimizer,
    "_validate_checkpoint_manifest": _validate_checkpoint_manifest,
    "save_weights_for_sampler": save_weights_for_sampler,
    "save_sampler_with_download_url": save_sampler_with_download_url,
}.items():
    setattr(UnslothEngine, _name, _fn)

__all__ = [
    "UnslothEngine",
    "_BatchPlan",
    "_best_attn_backend",
    "_checkpoint_target",
    "_configure_unsloth_environment",
    "_effective_attn_implementation",
    "_effective_fast_inference",
    "_effective_gpu_memory_utilization",
    "_effective_vllm_standby",
    "_flash_attention_2_available",
    "_flash_attention_3_available",
    "_gpu_compute_capability",
    "_load_model",
    "_model_device",
    "_module_available",
    "_padding_free_forced",
    "_padding_free_requested",
    "_requires_transformers_5_for_qwen3_5",
    "_save_weights",
    "_set_attention_implementation",
    "_setup_distributed",
    "_speed",
    "_torch_dtype",
    "_unwrap_model",
    "_wrap_distributed_model",
    "compute_logprobs",
    "forward",
    "forward_backward",
    "forward_backward_custom",
    "get_info",
    "get_tokenizer",
    "load_state",
    "load_state_with_optimizer",
    "optim_step",
    "register_custom_loss",
    "sample",
    "save_sampler_with_download_url",
    "save_state",
    "save_weights_for_sampler",
]
